### ISSUE TITLE
is there a solution for the material of a product?

### ISSUE THREAD

**Issue by SharonCastel** [nicobritos/python-faker-commerce#1]

**Comment by Sergi7531** [comment]
ICYMI:

I have submitted [a pull request](https://github.com/nicobritos/python-faker-commerce/pull/3) that addresses this exact issue you're mentioning. As of now, @nicobritos has answered with an OK so we'll hopefully get it to main soon. 

Will provide updates as they happen!

PS: Bit late, sorry I didn't get to see the issue before

**Comment by SharonCastel** [comment]
Better late than never!
Thanks a lot for that!

**Comment by nicobritos** [comment]
Hi! Released on 1.0.4. Thanks @Sergi7531 for the PR
